export const ROLES_KEY = "roles";
export const accessMatrix = {
	admins: ["superadmin", "admin"],
	doctors: ["superadmin", "admin", "head_doctor", "doctor"],
	patients: [
		"superadmin",
		"admin",
		"head_doctor",
		"doctor",
		"manager",
		"patient",
	],
	staffs: ["superadmin", "admin", "head_doctor", "manager", "staff"],
	appointments: [
		"superadmin",
		"admin",
		"head_doctor",
		"doctor",
		"manager",
		"staff",
		"patient",
	],
	medical_records: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	med_prescription: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	schedules: ["superadmin", "admin", "head_doctor", "doctor"],
	departments: ["superadmin", "admin", "head_doctor", "manager"],
	services: ["superadmin", "admin", "head_doctor", "manager"],
	payments: ["superadmin", "admin", "manager", "doctor","patient"],
	rooms: ["superadmin", "admin", "head_doctor", "manager"],
	room_types: ["superadmin", "admin", "head_doctor", "manager"],
	patient_admissions: [
		"superadmin",
		"admin",
		"head_doctor",
		"doctor",
		"manager",
		"patient",
	],
	lab: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	med_history: ["superadmin", "admin", "head_doctor", "patient"],
};
