export const ROLES_KEY = "roles";
export const WeekDays = [
	"Sunday",
	"Monday",
	"Tuesday",
	"Wednesday",
	"Thursday",
	"Friday",
	"Saturday",
];
export const accessMatrix = {
	admins: ["superadmin", "admin"],
	doctors: ["superadmin", "admin", "head_doctor", "doctor"],
	patients: [
		"superadmin",
		"admin",
		"head_doctor",
		"doctor",
		"manager",
		"patient",
	],
	staffs: ["superadmin", "admin", "head_doctor", "manager", "staff"],
	appointments: [
		"superadmin",
		"admin",
		"head_doctor",
		"doctor",
		"manager",
		"staff",
		"patient",
	],
	medical_records: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	med_prescription: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	schedules: ["superadmin", "admin", "head_doctor", "doctor"],
	departments: ["superadmin", "admin", "head_doctor", "manager"],
	services: ["superadmin", "admin", "head_doctor", "manager"],
	payments: ["superadmin", "admin", "manager", "doctor", "patient"],
	rooms: ["superadmin", "admin", "staff", "manager"],
	room_types: ["superadmin", "admin", "manager", "staff"],
	patient_admissions: [
		"superadmin",
		"admin",
		"head_doctor",
		"manager",
		"staff",
	],
	lab: ["superadmin", "admin", "head_doctor", "doctor", "patient"],
	med_history: ["superadmin", "admin", "head_doctor", "patient"],
	medicine_categories: ["superadmin", "admin", "staff"],
	medicines: ["superadmin", "admin", "staff"],
};
